<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$applicationConfig = array(
    'modules' => array(
        'IyvZF2Generic',
        'Core',

    ),
    'module_listener_options' => array(
        'config_cache_enabled' => false,
        'configCacheKey' => 'APPLICATION_ENV-1409764256.0331',
        'cache_dir' => 'data/cache/',
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
            'config/environment.php'
        )
    )
);

if (APPLICATION_ENV === 'development') {
    $applicationConfig['modules'][] = 'BjyProfiler';
    $applicationConfig['modules'][] = 'ZendDeveloperTools';
    $applicationConfig['modules'][] = 'IyvZF2PommProfiler';
}

return $applicationConfig;
