<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Core\Pomm\Zf2skeleton\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Page
 *
 * Structure class for relation public.page.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Page extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.page')
            ->setPrimaryKey(['page_id'])
            ->addField('page_id', 'int2')
            ->addField('name', 'varchar')
            ->addField('content', 'text')
            ;
    }
}
